import { BanciFormularioCampo } from '../../core/models/banci-formulario.models';

export const CAMPOS_CARPETAS: BanciFormularioCampo[] = [
  {"clave": "id_ci", "etiqueta": "Identificador de carpeta (ID_CI)", "tipo": "text", "obligatorio": true, "maximo": 250, "ayuda": "Debe ser único dentro de la entidad, independientemente de la fecha."},
  {"clave": "ntra_ci", "etiqueta": "Nomenclatura de la carpeta (NTRA_CI)", "tipo": "text", "obligatorio": true, "maximo": 250},
  {"clave": "fha_de_ini", "etiqueta": "Fecha de inicio", "tipo": "date", "obligatorio": true},
  {"clave": "hra_de_ini", "etiqueta": "Hora de inicio", "tipo": "time"},
  {"clave": "rmen_de_hchos", "etiqueta": "Resumen de hechos", "tipo": "textarea", "maximo": 20000},
  {"clave": "ord_apreh", "etiqueta": "Orden de aprehensión", "tipo": "text", "maximo": 100, "ayuda": "Entero mayor o igual a cero; deje vacío si está pendiente."},
  {"clave": "fgran", "etiqueta": "Flagrancia", "tipo": "text", "maximo": 100, "ayuda": "Entero mayor o igual a cero; deje vacío si está pendiente."},
  {"clave": "ctaon", "etiqueta": "Citación", "tipo": "text", "maximo": 100, "ayuda": "Entero mayor o igual a cero; deje vacío si está pendiente."},
  {"clave": "td_v_ap", "etiqueta": "Total de vinculaciones a proceso", "tipo": "text", "maximo": 100, "ayuda": "Debe coincidir con orden de aprehensión + flagrancia + citación."},
  {"clave": "proc_abrev", "etiqueta": "Procedimiento abreviado", "tipo": "text", "maximo": 100, "ayuda": "Entero mayor o igual a cero; deje vacío si está pendiente."},
  {"clave": "juc_oral", "etiqueta": "Juicio oral", "tipo": "text", "maximo": 100, "ayuda": "Entero mayor o igual a cero; deje vacío si está pendiente."},
  {"clave": "td_sen_con", "etiqueta": "Total de sentencias condenatorias", "tipo": "text", "maximo": 100, "ayuda": "Debe coincidir con procedimiento abreviado + juicio oral."},
  {"clave": "no_ejer_acc_pnal", "etiqueta": "No ejercicio de la acción penal", "tipo": "text", "maximo": 100, "ayuda": "Entero mayor o igual a cero; deje vacío si está pendiente."},
  {"clave": "otra", "etiqueta": "Otra determinación", "tipo": "text", "maximo": 100, "ayuda": "Entero mayor o igual a cero; deje vacío si está pendiente."},
  {"clave": "dic", "etiqueta": "Derivación por incompetencia", "tipo": "text", "maximo": 100, "ayuda": "Entero mayor o igual a cero; deje vacío si está pendiente."},
];

export const CAMPOS_DELITOS: BanciFormularioCampo[] = [
  {"clave": "id_delito", "etiqueta": "Identificador de delito (ID_DELITO)", "tipo": "text", "obligatorio": true, "maximo": 250},
  {"clave": "dto", "etiqueta": "Descripción del delito", "tipo": "text", "obligatorio": true, "maximo": 500},
  {"clave": "moda_dto", "etiqueta": "Modalidad del delito", "tipo": "text", "obligatorio": true, "maximo": 2000},
  {"clave": "forma_acc", "etiqueta": "Forma de acción", "tipo": "select", "obligatorio": true},
  {"clave": "fha_de_hchos", "etiqueta": "Fecha de los hechos", "tipo": "date"},
  {"clave": "hra_de_hchos", "etiqueta": "Hora de los hechos", "tipo": "time"},
  {"clave": "emto_com_dto", "etiqueta": "Instrumento de comisión", "tipo": "select", "obligatorio": true},
  {"clave": "grdo_cons", "etiqueta": "Grado de consumación", "tipo": "select", "obligatorio": true},
  {"clave": "clasf_de_dto", "etiqueta": "Clasificación del delito", "tipo": "select", "obligatorio": true},
  {"clave": "id_ent_hchos", "etiqueta": "Entidad de los hechos", "tipo": "select", "obligatorio": true},
  {"clave": "id_mun_hchos", "etiqueta": "Municipio de los hechos", "tipo": "select", "obligatorio": true},
  {"clave": "nom_loc_hchos", "etiqueta": "Localidad de los hechos", "tipo": "text", "maximo": 500},
  {"clave": "id_loc_hchos", "etiqueta": "Clave de localidad", "tipo": "text", "maximo": 250},
  {"clave": "nom_col_hchos", "etiqueta": "Colonia de los hechos", "tipo": "text", "maximo": 500},
  {"clave": "id_col_hchos", "etiqueta": "Clave de colonia", "tipo": "text", "maximo": 250},
  {"clave": "cp", "etiqueta": "Código postal", "tipo": "text", "maximo": 10},
  {"clave": "coord_x", "etiqueta": "Coordenada X", "tipo": "text", "maximo": 100},
  {"clave": "coord_y", "etiqueta": "Coordenada Y", "tipo": "text", "maximo": 100},
  {"clave": "dom_hchos", "etiqueta": "Domicilio de los hechos", "tipo": "textarea", "maximo": 20000},
];

export const CAMPOS_VICTIMAS: BanciFormularioCampo[] = [
  {"clave": "id_vicf", "etiqueta": "Identificador de víctima (ID_VICF)", "tipo": "text", "obligatorio": true, "maximo": 250},
  {"clave": "id_tv", "etiqueta": "Tipo de víctima", "tipo": "select", "obligatorio": true},
  {"clave": "id_tpm", "etiqueta": "Tipo de persona moral", "tipo": "select"},
  {"clave": "sexo", "etiqueta": "Sexo", "tipo": "select"},
  {"clave": "genero", "etiqueta": "Género", "tipo": "select"},
  {"clave": "pob", "etiqueta": "Pertenencia a población indígena", "tipo": "select"},
  {"clave": "disc", "etiqueta": "Discapacidad", "tipo": "select"},
  {"clave": "fha_nac", "etiqueta": "Fecha de nacimiento", "tipo": "date"},
  {"clave": "edad", "etiqueta": "Edad", "tipo": "text", "maximo": 100},
  {"clave": "nacional", "etiqueta": "Nacionalidad", "tipo": "select"},
  {"clave": "folio_fotovolante", "etiqueta": "Folio del fotovolante", "tipo": "text", "maximo": 250},
  {"clave": "folio_rnpdno", "etiqueta": "Folio RNPDNO", "tipo": "text", "maximo": 250},
  {"clave": "pro_apellido", "etiqueta": "Primer apellido", "tipo": "text", "maximo": 250},
  {"clave": "sdo_apellido", "etiqueta": "Segundo apellido", "tipo": "text", "maximo": 250},
  {"clave": "nomb", "etiqueta": "Nombre(s)", "tipo": "text", "maximo": 500},
  {"clave": "entidad_nacimiento", "etiqueta": "Entidad de nacimiento", "tipo": "text", "maximo": 250},
  {"clave": "estado_migratorio", "etiqueta": "Estado migratorio", "tipo": "text", "maximo": 500},
  {"clave": "curp", "etiqueta": "CURP", "tipo": "text", "maximo": 50},
  {"clave": "rfc", "etiqueta": "RFC", "tipo": "text", "maximo": 13},
  {"clave": "fecha_ultimo_contacto", "etiqueta": "Fecha del último contacto", "tipo": "date"},
  {"clave": "hora_ultimo_contacto", "etiqueta": "Hora del último contacto", "tipo": "time"},
  {"clave": "entidad_visto", "etiqueta": "Entidad donde fue vista", "tipo": "text", "maximo": 250},
  {"clave": "municipio_visto", "etiqueta": "Municipio donde fue vista", "tipo": "text", "maximo": 250},
  {"clave": "lugar_ultimo_contacto", "etiqueta": "Lugar del último contacto", "tipo": "textarea", "maximo": 20000},
  {"clave": "senas_tatuaje_datos_identificacion", "etiqueta": "Señas, tatuajes y datos de identificación", "tipo": "textarea", "maximo": 20000},
  {"clave": "localizado_o_no_localizado", "etiqueta": "Estado de localización", "tipo": "select"},
  {"clave": "con_o_sin_vida", "etiqueta": "Condición de vida", "tipo": "select"},
  {"clave": "fecha_localizacion", "etiqueta": "Fecha de localización", "tipo": "date"},
  {"clave": "voluntaria", "etiqueta": "Ausencia voluntaria", "tipo": "select"},
  {"clave": "fue_delito", "etiqueta": "¿Fue víctima de un delito?", "tipo": "select"},
  {"clave": "delito", "etiqueta": "Delito del que fue víctima", "tipo": "text", "maximo": 1000},
  {"clave": "obs", "etiqueta": "Observaciones", "tipo": "textarea", "maximo": 20000},
];

