import { BanciFormularioCampo } from '../../core/models/banci-formulario.models';

export const CAMPOS_CARPETAS: BanciFormularioCampo[] = [
  {
    clave: 'id_ci',
    etiqueta: 'Identificador de carpeta (ID_CI)',
    tipo: 'text',
    obligatorio: true,
    maximo: 250,
    ayuda: 'Debe ser único dentro de la entidad.',
  },
  {
    clave: 'ntra_ci',
    etiqueta: 'Nomenclatura de la carpeta (NTRA_CI)',
    tipo: 'text',
    obligatorio: true,
    maximo: 250,
  },
  { clave: 'fha_de_ini', etiqueta: 'Fecha de inicio', tipo: 'date', obligatorio: true },
  { clave: 'hra_de_ini', etiqueta: 'Hora de inicio', tipo: 'time' },
  { clave: 'rmen_de_hchos', etiqueta: 'Resumen de hechos', tipo: 'textarea', maximo: 20000 },
];

export const CAMPOS_DELITOS: BanciFormularioCampo[] = [
  {
    clave: 'id_delito',
    etiqueta: 'Identificador de delito (ID_DELITO)',
    tipo: 'text',
    obligatorio: true,
    maximo: 250,
  },
  {
    clave: 'dto',
    etiqueta: 'Descripción del delito',
    tipo: 'text',
    obligatorio: true,
    maximo: 2000,
  },
  {
    clave: 'moda_dto',
    etiqueta: 'Modalidad del delito',
    tipo: 'text',
    obligatorio: true,
    maximo: 2000,
  },
  { clave: 'forma_acc', etiqueta: 'Forma de acción', tipo: 'select', obligatorio: true },
  { clave: 'fha_de_hchos', etiqueta: 'Fecha de los hechos', tipo: 'date' },
  { clave: 'hra_de_hchos', etiqueta: 'Hora de los hechos', tipo: 'time' },
  { clave: 'emto_com_dto', etiqueta: 'Instrumento de comisión', tipo: 'select', obligatorio: true },
  { clave: 'grdo_cons', etiqueta: 'Grado de consumación', tipo: 'select', obligatorio: true },
  {
    clave: 'clasf_de_dto',
    etiqueta: 'Clasificación del delito',
    tipo: 'select',
    obligatorio: true,
  },
  { clave: 'id_ent_hchos', etiqueta: 'Entidad de los hechos', tipo: 'select', obligatorio: true },
  { clave: 'id_mun_hchos', etiqueta: 'Municipio de los hechos', tipo: 'select', obligatorio: true },
  { clave: 'nom_loc_hchos', etiqueta: 'Localidad de los hechos', tipo: 'text', maximo: 500 },
  { clave: 'id_loc_hchos', etiqueta: 'Clave de localidad', tipo: 'text', maximo: 250 },
  { clave: 'nom_col_hchos', etiqueta: 'Colonia de los hechos', tipo: 'text', maximo: 500 },
  { clave: 'id_col_hchos', etiqueta: 'Clave de colonia', tipo: 'text', maximo: 250 },
  { clave: 'cp', etiqueta: 'Código postal', tipo: 'text', maximo: 10 },
  { clave: 'coord_x', etiqueta: 'Coordenada X', tipo: 'text', maximo: 100 },
  { clave: 'coord_y', etiqueta: 'Coordenada Y', tipo: 'text', maximo: 100 },
  { clave: 'dom_hchos', etiqueta: 'Domicilio de los hechos', tipo: 'textarea', maximo: 20000 },
];

export const CAMPOS_VICTIMAS: BanciFormularioCampo[] = [
  {
    clave: 'id_vicf',
    etiqueta: 'Identificador de víctima (ID_VICF)',
    tipo: 'text',
    obligatorio: true,
    maximo: 250,
  },
  { clave: 'id_tv', etiqueta: 'Tipo de víctima', tipo: 'select', obligatorio: true },
  { clave: 'id_tpm', etiqueta: 'Tipo de persona moral', tipo: 'select' },
  { clave: 'sexo', etiqueta: 'Sexo', tipo: 'select' },
  { clave: 'genero', etiqueta: 'Género', tipo: 'select' },
  { clave: 'pob', etiqueta: 'Pertenencia a población indígena', tipo: 'select' },
  { clave: 'disc', etiqueta: 'Discapacidad', tipo: 'select' },
  { clave: 'fha_nac', etiqueta: 'Fecha de nacimiento', tipo: 'date' },
  { clave: 'edad', etiqueta: 'Edad', tipo: 'text', maximo: 3 },
  { clave: 'nacional', etiqueta: 'Nacionalidad', tipo: 'select' },

  { clave: 'folio_rnpdno', etiqueta: 'Folio RNPDNO', tipo: 'text', obligatorio: true, maximo: 250 },
  { clave: 'pro_apellido', etiqueta: 'Primer apellido', tipo: 'text', maximo: 250 },
  { clave: 'sdo_apellido', etiqueta: 'Segundo apellido', tipo: 'text', maximo: 250 },
  { clave: 'nomb', etiqueta: 'Nombre(s)', tipo: 'text', maximo: 500 },
  { clave: 'entidad_nacimiento', etiqueta: 'Entidad de nacimiento', tipo: 'text', maximo: 250 },
  { clave: 'estado_migratorio', etiqueta: 'Estado migratorio', tipo: 'text', maximo: 500 },
  {
    clave: 'curp',
    etiqueta: 'CURP',
    tipo: 'text',
    maximo: 18,
    ayuda: 'Opcional. Si se informa, se validará su formato y se consultará RENAPO.',
  },
  { clave: 'rfc', etiqueta: 'RFC', tipo: 'text', maximo: 13 },
];
